---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: oisys
    tier: frontend
    role: master
spec:
  ports:
  - port: 30001
    targetPort: 80
    protocol: TCP
    nodePort: 32164
  selector:
    app: oisys
    tier: frontend
    role: master
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oisys
spec:
  selector:
    matchLabels:
      app: oisys
      role: master
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: oisys
        role: master
        tier: frontend
    spec:
      containers:
        - name: front-end
          image: vonaerich/oisys-frontend:test
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Kube
            - name: ConnectionStrings__OisysDb
              value: Server=db;Database=OisysDatabase;User Id=sa;Password=Password123!
---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: sqlserver
    tier: backend
spec:
  ports:
  - port: 1433
    targetPort: 1433
    protocol: TCP
  selector:
    app: sqlserver
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: sqlserver
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: sqlserver
        tier: backend
    spec:
      containers:
      - name: sql-server
        image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
        ports:
          - containerPort: 1433
        env:
          - name: ACCEPT_EULA
            value: 'Y'
          - name: SA_PASSWORD
            value: Password123!